/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_EBLA_NET_EBLAFACE_H_
#define JSONRPC_CPP_STUB_EBLA_NET_EBLAFACE_H_

#include <libweb3jsonrpc/ModularServer.h>

namespace ebla {
namespace net {
class EblaFace : public ServerInterface<EblaFace> {
 public:
  static constexpr int JSON_ANY = 0;

  EblaFace() {
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_protocolVersion", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, NULL),
        &ebla::net::EblaFace::ebla_protocolVersionI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_getVersion", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, NULL),
        &ebla::net::EblaFace::ebla_getVersionI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_getDagBlockByHash", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",
                           jsonrpc::JSON_STRING, "param2", jsonrpc::JSON_BOOLEAN, NULL),
        &ebla::net::EblaFace::ebla_getDagBlockByHashI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_getDagBlockByLevel", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",
                           jsonrpc::JSON_STRING, "param2", jsonrpc::JSON_BOOLEAN, NULL),
        &ebla::net::EblaFace::ebla_getDagBlockByLevelI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_dagBlockLevel", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, NULL),
        &ebla::net::EblaFace::ebla_dagBlockLevelI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_dagBlockPeriod", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, NULL),
        &ebla::net::EblaFace::ebla_dagBlockPeriodI);
    this->bindAndAddMethod(jsonrpc::Procedure("ebla_getScheduleBlockByPeriod", jsonrpc::PARAMS_BY_POSITION,
                                              jsonrpc::JSON_OBJECT, "param1", jsonrpc::JSON_STRING, NULL),
                           &ebla::net::EblaFace::ebla_getScheduleBlockByPeriodI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_getNodeVersions", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, NULL),
        &ebla::net::EblaFace::ebla_getNodeVersionsI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_getConfig", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, NULL),
        &ebla::net::EblaFace::ebla_getConfigI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_getChainStats", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, NULL),
        &ebla::net::EblaFace::ebla_getChainStatsI);
    this->bindAndAddMethod(jsonrpc::Procedure("ebla_pbftBlockHashByPeriod", jsonrpc::PARAMS_BY_POSITION,
                                              jsonrpc::JSON_STRING, "param1", jsonrpc::JSON_STRING, NULL),
                           &ebla::net::EblaFace::ebla_pbftBlockHashByPeriodI);
    this->bindAndAddMethod(
        jsonrpc::Procedure("ebla_yield", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param1", JSON_ANY, NULL),
        &ebla::net::EblaFace::ebla_yieldI);
    this->bindAndAddMethod(jsonrpc::Procedure("ebla_totalSupply", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING,
                                              "param1", JSON_ANY, NULL),
                           &ebla::net::EblaFace::ebla_totalSupplyI);
  }

  inline virtual void ebla_protocolVersionI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_protocolVersion();
  }
  inline virtual void ebla_getVersionI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_getVersion();
  }
  inline virtual void ebla_getDagBlockByHashI(const Json::Value &request, Json::Value &response) {
    response = this->ebla_getDagBlockByHash(request[0u].asString(), request[1u].asBool());
  }
  inline virtual void ebla_getDagBlockByLevelI(const Json::Value &request, Json::Value &response) {
    response = this->ebla_getDagBlockByLevel(request[0u].asString(), request[1u].asBool());
  }
  inline virtual void ebla_dagBlockLevelI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_dagBlockLevel();
  }
  inline virtual void ebla_dagBlockPeriodI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_dagBlockPeriod();
  }
  inline virtual void ebla_getScheduleBlockByPeriodI(const Json::Value &request, Json::Value &response) {
    response = this->ebla_getScheduleBlockByPeriod(request[0u].asString());
  }
  inline virtual void ebla_getNodeVersionsI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_getNodeVersions();
  }
  inline virtual void ebla_getConfigI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_getConfig();
  }
  inline virtual void ebla_getChainStatsI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_getChainStats();
  }
  inline virtual void ebla_pbftBlockHashByPeriodI(const Json::Value &request, Json::Value &response) {
    response = this->ebla_pbftBlockHashByPeriod(request[0u].asString());
  }
  inline virtual void ebla_yieldI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_yield(request[0u].asString());
  }
  inline virtual void ebla_totalSupplyI(const Json::Value &request, Json::Value &response) {
    (void)request;
    response = this->ebla_totalSupply(request[0u].asString());
  }

  virtual std::string ebla_protocolVersion() = 0;
  virtual Json::Value ebla_getVersion() = 0;
  virtual Json::Value ebla_getDagBlockByHash(const std::string &param1, bool param2) = 0;
  virtual Json::Value ebla_getDagBlockByLevel(const std::string &param1, bool param2) = 0;
  virtual std::string ebla_dagBlockLevel() = 0;
  virtual std::string ebla_dagBlockPeriod() = 0;
  virtual Json::Value ebla_getScheduleBlockByPeriod(const std::string &param1) = 0;
  virtual Json::Value ebla_getNodeVersions() = 0;
  virtual Json::Value ebla_getConfig() = 0;
  virtual Json::Value ebla_getChainStats() = 0;
  virtual std::string ebla_pbftBlockHashByPeriod(const std::string &param1) = 0;
  virtual std::string ebla_yield(const std::string &param1) = 0;
  virtual std::string ebla_totalSupply(const std::string &param1) = 0;
};

}  // namespace net
}  // namespace ebla
#endif  // JSONRPC_CPP_STUB_EBLA_NET_EBLAFACE_H_
